# Generated by Django 5.0.4 on 2024-12-17 09:19

import django.db.models.deletion
import django.utils.timezone
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('VD', 'وحدت'), ('AN', 'اندیشه'), ('SB', 'صبا')], default='VD', max_length=2)),
                ('capacity', models.IntegerField(max_length=5)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('Saturday', 'شنبه'), ('Sunday', 'یک\u200cشنبه'), ('Monday', 'دو\u200cشنبه'), ('Tuesday', 'سه\u200cشنبه'), ('Wednesday', 'چهارشنبه')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_reserved', models.BooleanField(default=False)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='reservations.hall')),
            ],
        ),
        migrations.CreateModel(
            name='ReservationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='نام و نام خانوادگی')),
                ('student_id', models.CharField(max_length=20, verbose_name='شماره دانشجویی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='شماره تماس')),
                ('event_topic', models.CharField(max_length=200, verbose_name='عنوان و موضوع مراسم')),
                ('date', django_jalali.db.models.jDateField()),
                ('status', models.CharField(choices=[('PN', 'در حال بررسی'), ('AP', 'تایید شده'), ('RJ', 'رد شده')], default='PN', max_length=2)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.hall')),
                ('time_slots', models.ManyToManyField(to='reservations.timeslot')),
            ],
        ),
    ]
