# Generated by Django 5.0.4 on 2024-12-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='capacity',
            field=models.IntegerField(),
        ),
    ]
