# Generated by Django 5.0.4 on 2024-12-19 09:45

import django.db.models.deletion
import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Halls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('image', models.ImageField(upload_to='halls_images/')),
            ],
            options={
                'verbose_name': 'تالار',
                'verbose_name_plural': 'تالار ها',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('event_date', django_jalali.db.models.jDateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('RJ', 'رد شده'), ('AP', 'تایید شده'), ('PN', 'در حال انتظار')], default='PN', max_length=2)),
                ('student_id', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('created', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='halls.halls', verbose_name='تالار')),
            ],
            options={
                'verbose_name': 'رویداد',
                'verbose_name_plural': 'رویداد ها',
                'ordering': ['-created'],
                'indexes': [models.Index(fields=['-created'], name='halls_event_created_0d0eaf_idx')],
            },
        ),
    ]
