# Generated by Django 5.0.4 on 2024-12-19 14:53

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.SlugField(blank=True, default='evnt', max_length=10, null=True, verbose_name='اسلاگ'),
        ),
        migrations.AddField(
            model_name='halls',
            name='slug',
            field=models.SlugField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(verbose_name='زمان پایان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone_number',
            field=models.CharField(max_length=15, verbose_name='شماره تماس'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(verbose_name='زمان شروع'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('RJ', 'رد شده'), ('AP', 'تایید شده'), ('PN', 'در حال انتظار')], default='PN', max_length=2, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='event',
            name='student_id',
            field=models.CharField(max_length=20, verbose_name='شماره دانشجویی'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
