# Generated by Django 5.0.4 on 2024-12-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0002_event_description_event_slug_halls_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='student_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='شماره دانشجویی'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='address',
            field=models.TextField(verbose_name='آدرس تالار'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='ظرفیت تالار'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='image',
            field=models.ImageField(upload_to='halls_images/', verbose_name='تصویر تالار'),
        ),
        migrations.AlterField(
            model_name='halls',
            name='name',
            field=models.CharField(max_length=100, verbose_name='نام تالار'),
        ),
    ]
