# Generated by Django 5.0.4 on 2024-12-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0003_alter_event_student_id_alter_halls_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halls',
            name='name',
            field=models.CharField(choices=[('VD', 'وحدت'), ('AN', 'اندیشه'), ('SB', 'صبا')], max_length=2, verbose_name='نام تالار'),
        ),
    ]
