# Generated by Django 5.1.4 on 2025-10-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('halls', '0006_alter_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='posters/placeholder.svg', upload_to='posters/', verbose_name='تصویر پوستر'),
        ),
    ]
